$primary = rgb(22c353)
$surface = rgb(e0ebe3)
$secondary = rgb(a39329)
$error = rgb(fd4663)
$tertiary = rgb(63862d)
$surface_lowest = rgb(f3f7f4)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
