general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    color = rgba(0, 0, 0, 0)
}

input-field {
    monitor =
    size = 280, 48
    outline_thickness = 2
    outer_color = rgba(0, 210, 255, 0.6)
    inner_color = rgba(0, 0, 0, 0.85)
    font_color = rgba(255, 255, 255, 1.0)
    fade_on_empty = true
    placeholder_text = 󰌾 password
    rounding = 6
    position = 0, -80
    halign = center
    valign = center
}
