# Prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Général
set -g default-terminal "screen-256color"
set -g history-limit 10000
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g display-time 300
set -g bell-action none
set -g monitor-activity on
set -g visual-activity on

# Splits (tes binds Alt)
unbind '"'
unbind %
bind -n M-= split-window -h -c "#{pane_current_path}"
bind -n M-- split-window -v -c "#{pane_current_path}"

# Navigation Alt (tes binds)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Resize Alt (tes binds)
bind -nr M-H resize-pane -L 5
bind -nr M-J resize-pane -D 5
bind -nr M-K resize-pane -U 5
bind -nr M-L resize-pane -R 5

# Pane/window
bind -n M-q kill-pane
bind c new-window -c "#{pane_current_path}"
bind C new-session
bind x kill-window
bind Tab next-window
bind BTab previous-window
bind p paste-buffer

# Vi copy mode
set -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Reload
bind r source-file ~/.config/tmux/tmux.conf \; display "Config rechargée!"

# Colors
# Couleurs par défaut (si matugen n'a pas encore tourné)
set -gq @thm_bg        "#1b1c15"
set -gq @thm_fg        "#e4e4cf"
set -gq @thm_primary   "#bfcf67"

# Source le fichier généré par matugen
source-file ~/.config/tmux/generated.conf

set -g window-style 'bg=default'
set -g window-active-style 'bg=default'
set -g pane-border-style 'bg=default'
set -g pane-active-border-style 'bg=default'

# Status bar
set -g status-position bottom
set -g status-style bg=default,fg=default
#set -g window-status-current-style bg=default,fg=#{@thm_primary},bold
set -g window-status-separator " |"
set -g window-status-format "#[fg=#{@thm_surface_variant}]#{?window_activity_flag,╺, }#[fg=#{@thm_fg}][ #I #W ]"
set -g window-status-current-format "#[fg=#{@thm_primary}] (#[fg=#{@thm_fg}] #I #W#[fg=#{@thm_primary}] )"
set -g window-status-activity-style none
set -g status-left "#[fg=#{@thm_primary}][#[fg=#{@thm_fg}]#S#[fg=#{@thm_primary}]]#[fg=#{@thm_text_variant}] -"
set -g status-right "#[fg=#{@thm_text_variant}].../#(basename #{pane_current_path}) #[fg=#{@thm_fg}]- #[fg=#{@thm_primary}]#(whoami)#[fg=#{@thm_text_variant}]@#[fg=#{@thm_outline}]#H #[fg=#{@thm_text_variant}]- %H:%M"
